# Generated by Django 3.1 on 2021-09-18 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210818_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at'], 'permissions': [('manage_blogs', 'Manage blogs.')]},
        ),
    ]
