# Generated by Django 3.1 on 2021-08-18 06:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import koytola.core.db.fields
import koytola.core.utils.editorjs


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.CharField(blank=True, max_length=320, null=True)),
                ('content', koytola.core.db.fields.SanitizedJSONField(blank=True, default=dict, sanitizer=koytola.core.utils.editorjs.clean_editor_js)),
                ('link', models.URLField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('audience', models.CharField(choices=[('public', 'Represents public news or announcement'), ('platform', 'News dedicated to users in the platform'), ('staff', 'News for staff members'), ('other', 'News for other audience type')], default='other', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['slug'],
                'permissions': [('manage_news', 'Manage news.')],
            },
        ),
        migrations.CreateModel(
            name='NewsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=70, null=True, validators=[django.core.validators.MaxLengthValidator(70)])),
                ('seo_description', models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.MaxLengthValidator(300)])),
                ('language_code', models.CharField(max_length=10)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=320)),
                ('content', koytola.core.db.fields.SanitizedJSONField(blank=True, default=dict, sanitizer=koytola.core.utils.editorjs.clean_editor_js)),
                ('content_plaintext', models.TextField(blank=True, default='')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.news')),
            ],
            options={
                'ordering': ['language_code', 'news', 'pk'],
                'unique_together': {('language_code', 'news')},
            },
        ),
    ]
