# Generated by Django 3.1 on 2021-08-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer company type'), ('supplier', 'Supplier company type')], default='manufacturer', max_length=250),
        ),
    ]
