# Generated by Django 3.1 on 2021-08-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20210827_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='content_plaintext',
            field=models.TextField(blank=True, max_length=65500, null=True),
        ),
    ]
