# Generated by Django 3.1 on 2021-08-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='browser_version',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
